[package]
name = "macos-unifiedlogs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde_json = "1.0.91"
serde = {version="1.0.152", features = ["derive"]}
log = "0.4.17"
lz4_flex = "0.9.5"
byteorder = "1.4.3"
plist = "1.4.0"
regex = "1.7.1"
base64 = "0.21.0"
chrono = "0.4.23"
memmap = "0.7.0"

[dev-dependencies]
simplelog = "0.12.0"
csv = "1.1.6"
chrono = "0.4.23"
criterion = "0.4.0"

[[bench]]
name = "high_sierra_benchmark"
harness = false

[[bench]]
name = "big_sur_benchmark"
harness = false

[[bench]]
name = "monterey_benchmark"
harness = false
